apiVersion: apps/v1
kind: Deployment
metadata:
  name: windpowerplatforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windpowerplatformservice
  template:
    metadata:
      labels:
        app: windpowerplatformservice
    spec:
      containers:
        - name: windpowerplatformservice 
          image: petrenkodocker/windpowerplatformservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: windpowerplatforms-clusterip-srv
spec: 
  type: ClusterIP
  selector:
    app: windpowerplatformservice
  ports: 
  - name: windpowerplatformservice
    protocol: TCP
    port: 80
    targetPort: 80 
  - name: windpowerplatformgrpc
    protocol: TCP
    port: 755
    targetPort: 755